# Generated by Django 4.0.1 on 2022-01-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="employeerestaurant",
            table="employee_restaurant",
        ),
        migrations.AlterModelTable(
            name="restaurant",
            table="restaurant",
        ),
    ]
